<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox Terms And Condition checked</name>
   <tag></tag>
   <elementGuidId>275110e7-bdf1-4baf-8bb8-1757eff00187</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='terms-and-condition' and @checked]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#terms-and-condition</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc8e9a89-4abb-4c05-bcb8-0f87adab0fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TermsAndConditions_checkbox__input__hOK6h</value>
      <webElementGuid>0408492d-f8b6-45a5-9de6-4bd4f20d0389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terms-and-condition</value>
      <webElementGuid>6898eb89-d7ca-4e6a-b628-224390ccedac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>termsAndCondition</value>
      <webElementGuid>a72f29ea-4ce2-43c1-911d-ca08c11e70a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>56cab950-e761-4ae1-8bd5-5da1a127bd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms-and-condition&quot;)</value>
      <webElementGuid>d5127bb4-7e11-4483-88eb-393387b35fea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='terms-and-condition']</value>
      <webElementGuid>5e0c2638-519f-4dbe-b5e1-1e3b3a99b9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='safe-area']/div[2]/div[2]/div/div[8]/label/input</value>
      <webElementGuid>bbe4bf0f-4595-4c43-9f7a-31d0d02ecdd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[@id='terms-and-condition' and @checked]</value>
      <webElementGuid>942c0fdc-1420-4eb7-a919-080603a8d3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'terms-and-condition' and @name = 'termsAndCondition' and @type = 'checkbox']</value>
      <webElementGuid>6279a975-5dd2-4a10-afab-0a7c20eeb629</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
