<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input KabupatenKota</name>
   <tag></tag>
   <elementGuidId>f2b8daac-3567-4e3a-93e3-9a2a110817df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cityAndProvince']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cityAndProvince</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>542f7936-507a-4632-80cd-ed60872f2c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5f5d382e-2095-4cbf-af33-76aae3031059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete__field_vc5UL</value>
      <webElementGuid>bb608a1c-76a7-44e9-b96a-4c697e709c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cityAndProvince</value>
      <webElementGuid>98362daa-3932-4d99-977c-101cb71226f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cityAndProvince</value>
      <webElementGuid>b73bb9d1-d66f-4dca-90c9-e8f976a4543d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Kabupaten/Kota</value>
      <webElementGuid>73000d99-fa83-46d0-af11-c322547b26e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e018d63-27bc-4658-b4a6-80d39ab529e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>KOTA BOGOR</value>
      <webElementGuid>feeff57c-6986-4d74-a6fd-f597aaab5339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cityAndProvince&quot;)</value>
      <webElementGuid>88f23ecb-3971-43e1-a800-2b05d814d92e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cityAndProvince']</value>
      <webElementGuid>8a561af7-a2af-484d-be70-c8e314510cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='safe-area']/div[2]/div[2]/div/div[7]/div/input</value>
      <webElementGuid>69bbc95e-f29a-4a65-97a7-2da3ecf41b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[@id='cityAndProvince']</value>
      <webElementGuid>e3a55293-99a7-41a9-b708-5d7c70d7d9a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cityAndProvince' and @name = 'cityAndProvince' and @placeholder = 'Pilih Kabupaten/Kota' and @type = 'text']</value>
      <webElementGuid>82d12131-47c3-4737-bd0c-3ed0cc2cc617</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
